### ISSUE TITLE
AttributeError: module 'scriptifier.scriptifier' has no attribute 'run_as_script'

### ISSUE THREAD

**Issue by moon341** [benvigano/burner-process#3]
from scriptifier import *
def func_1(model):
    history=model.fit_generator(
        train_generator,
        steps_per_epoch=train_generator.n//train_generator.batch_size,
        epochs=20,initial_epoch=0,
        validation_data=validation_generator,
        validation_steps=validation_generator.n//validation_generator.batch_size,callbacks=[csv_logger,tb_cb,tb_cb1])
    return model,history
scriptified_func_1 = scriptifier.run_as_script()
out = scriptified_func_1(model)

**Comment by benvigano** [comment]
Hey, thanks for pointing that out! I corrected the code, try to update the package and you should be good to go :)

`pip install scriptifier==0.0.14`
