### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by derHeinzer** [benvigano/burner-process#4]
Good job. I encountered the same issue as several before me when trying to fit and predict tensorflow models in a loop. Your tool safed me, but unfortunately does not support thread safety. I fixed that by using temp directories instead of using your higher identifier logic, but have not been able to push my fix to your repo.

**Comment by benvigano** [comment]
Hello, sorry for the late reply. What issue precisely do you encounter when attempting to push?
